=== newsgate/SiteConfig/Template/tests/SearchFrontend/ProxyTestConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
            targetNamespace="http://www.121media.com/xsd/ProxyTestConfig" 
            xmlns="http://www.121media.com/xsd/ProxyTestConfig" 
            elementFormDefault="qualified" 
            xml:lang="en" 
            version="1.0">
  
  <xsd:annotation>
    <xsd:documentation>Proxy Test Configuration File XML Schema
    </xsd:documentation>
  </xsd:annotation>

  <xsd:element name="config" type="ConfigType"/>

  <xsd:complexType name="ConfigType">
    <xsd:annotation>
      <xsd:documentation>Element that contains parameters for Proxy Test.
      </xsd:documentation>
    </xsd:annotation>

    <xsd:sequence>
      <xsd:element name="execution_time" type="xsd:positiveInteger"/>
      <xsd:element name="threads_number" type="xsd:positiveInteger"/>
      
      <!-- Specify maximum possible delay for requests in microseconds. -->
      <xsd:element name="request_max_delay" type="xsd:positiveInteger"/>

      <xsd:element name="statistics">
      <xsd:complexType>
        <xsd:annotation>
          <xsd:documentation>Element that contains statistics related options.</xsd:documentation>
        </xsd:annotation>

        <xsd:attribute name="metering_dump" type="xsd:positiveInteger" use="required">
          <xsd:annotation>
            <xsd:documentation>Sets number of requests between statistical dumps.</xsd:documentation>
          </xsd:annotation>
        </xsd:attribute>

        <xsd:attribute name="per_url_stat" type="xsd:boolean" default="true">
          <xsd:annotation>
            <xsd:documentation>Sets number of requests between statistical dumps.</xsd:documentation>
          </xsd:annotation>
        </xsd:attribute>

      </xsd:complexType>
      </xsd:element>
      <!-- end of ConfigType::statistics -->

      <xsd:element name="request_constraints" type="RequestConstraintsType"/>
      <xsd:element name="url_list_file" type="xsd:string"/>
      <xsd:element name="http_proxy" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>

      <xsd:element name="request">
      <xsd:complexType>

        <xsd:annotation>
          <xsd:documentation>Element that contains information regarding
                             HTTP requests to be made.</xsd:documentation>
        </xsd:annotation>

        <xsd:sequence>
          <xsd:element name="scheduling" type="RequestSchedulingType"/>
          <xsd:element name="headers" 
                       type="RequestHeadersType" 
                       minOccurs="0" 
                       maxOccurs="1"/>
        </xsd:sequence>

      </xsd:complexType>
      </xsd:element>
      <!-- end of ConfigType::request -->

    </xsd:sequence>

  </xsd:complexType> 
  <!-- end of ConfigType -->

  <xsd:complexType name="RequestConstraintsType">  
    
    <xsd:annotation>
      <xsd:documentation>Element that defines request constraints.
      </xsd:documentation>
    </xsd:annotation>

    <xsd:attribute name="sampling_size" 
                   type="xsd:positiveInteger" 
                   use="required">
      <xsd:annotation>
        <xsd:documentation>Sets number of last requests to be used for 
                           checking constraints.</xsd:documentation>
      </xsd:annotation>
    </xsd:attribute>

    <xsd:attribute name="timeout" type="xsd:positiveInteger" use="required">
      <xsd:annotation>
        <xsd:documentation>Set maximum number of microseconds to wait for 
                           server response.
        </xsd:documentation>
      </xsd:annotation>
    </xsd:attribute>

    <xsd:attribute name="intended_time" type="xsd:positiveInteger" use="required">
      <xsd:annotation>
        <xsd:documentation>If valid response time exceeds number of 
                           microseconds specified response will be 
                           considered prolonged.
        </xsd:documentation>
      </xsd:annotation>
    </xsd:attribute>

    <xsd:attribute name="failed_percentage" type="Percentage" use="required">
      <xsd:annotation>
        <xsd:documentation>Specify which percentage of failed requests is 
                           allowed.</xsd:documentation>
      </xsd:annotation>
    </xsd:attribute>

    <xsd:attribute name="prolonged_percentage" type="Percentage" use="required">
      <xsd:annotation>
        <xsd:documentation>Specify which percentage of prolonged requests is 
                           allowed.</xsd:documentation>
      </xsd:annotation>
    </xsd:attribute>

  </xsd:complexType> 
  <!-- end of RequestConstraintsType -->

  <xsd:complexType name="RequestHeadersType">  
    
    <xsd:annotation>
      <xsd:documentation>HTTP request additional headers.</xsd:documentation>
    </xsd:annotation>

    <xsd:sequence>
      <xsd:element name="header" minOccurs="0" maxOccurs="unbounded">
      <xsd:complexType>

        <xsd:annotation>
          <xsd:documentation>Element that contains information regarding
                             specific HTTP request headers.</xsd:documentation>
        </xsd:annotation>

        <xsd:attribute name="name" type="xsd:string" use="required">
          <xsd:annotation>
            <xsd:documentation>Specifies HTTP header name.</xsd:documentation>
          </xsd:annotation>
        </xsd:attribute>

        <xsd:attribute name="value" type="xsd:string" use="required">
          <xsd:annotation>
            <xsd:documentation>Specifies HTTP header value.</xsd:documentation>
          </xsd:annotation>
        </xsd:attribute>

      </xsd:complexType>
      </xsd:element>
      <!-- end of RequestHeadersType::header -->

    </xsd:sequence>

  </xsd:complexType> 
  <!-- end of RequestHeadersType -->

  <xsd:complexType name="RequestSchedulingType">  
    
    <xsd:annotation>
      <xsd:documentation>Requests scheduling policy.</xsd:documentation>
    </xsd:annotation>

    <xsd:choice>
      <xsd:element name="stick_frequency" type="StickFrequencyType"/>
      <xsd:element name="preserve_frequency" type="PreserveFrequencyType"/>
    </xsd:choice>

  </xsd:complexType> 
  <!-- end of RequestSchedulingType -->

  <xsd:complexType name="StickFrequencyType">  
    
    <xsd:annotation>
      <xsd:documentation>Element that defines "stick frequency" request 
                         scheduling parameters.
      </xsd:documentation>
    </xsd:annotation>

    <xsd:attribute name="period" type="xsd:positiveInteger" use="required">
      <xsd:annotation>
        <xsd:documentation>Specify requests frequency period in 
                           microseconds.</xsd:documentation>
      </xsd:annotation>
    </xsd:attribute>

    <xsd:attribute name="requests" type="xsd:positiveInteger" default="1">
      <xsd:annotation>
        <xsd:documentation>Specify requests count for one period (default is 1).</xsd:documentation>
      </xsd:annotation>
    </xsd:attribute>

    <xsd:attribute name="decrease_by" 
                   type="xsd:nonNegativeInteger" 
                   default="0">
      <xsd:annotation>
        <xsd:documentation>Specify by which number of microseconds the requests 
                           frequency period will be decreased occasionally.
        </xsd:documentation>
      </xsd:annotation>
    </xsd:attribute>

    <xsd:attribute name="decrease_to" 
                   type="xsd:nonNegativeInteger" 
                   default="0">
      <xsd:annotation>
        <xsd:documentation>Specify up to which number of microseconds 
                           frequency period will be decreased.
        </xsd:documentation>
      </xsd:annotation>
    </xsd:attribute>

    <xsd:attribute name="decrease_every" 
                   type="xsd:positiveInteger" 
                   default="1">
      <xsd:annotation>
        <xsd:documentation>Specify how often (in seconds) frequency 
                           period should be decreased.
        </xsd:documentation>
      </xsd:annotation>
    </xsd:attribute>

  </xsd:complexType> 
  <!-- end of StickFrequencyType -->

  <xsd:complexType name="PreserveFrequencyType">  
    
    <xsd:annotation>
      <xsd:documentation>Element that defines "preserve original frequency" 
                         request scheduling parameters.
      </xsd:documentation>
    </xsd:annotation>

    <xsd:attribute name="tmp" type="xsd:positiveInteger" use="required">
      <xsd:annotation>
        <xsd:documentation>Specify desired requests frequency in 
                           microseconds.</xsd:documentation>
      </xsd:annotation>
    </xsd:attribute>

  </xsd:complexType> 
  <!-- end of PreserveFrequencyType -->

  <xsd:simpleType name="Percentage">
    <xsd:restriction base="xsd:nonNegativeInteger">
      <xsd:maxInclusive value="100"/>
    </xsd:restriction>
  </xsd:simpleType>

</xsd:schema>

=== newsgate/SiteConfig/Template/tests/SearchFrontend/ngtest.xml
<config xmlns="http://www.121media.com/xsd/ProxyTestConfig"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:schemaLocation="http://www.121media.com/xsd/ProxyTestConfig ./ProxyTestConfig.xsd">

  <execution_time>1800</execution_time>
  <threads_number>300</threads_number>
  <request_max_delay>1000000</request_max_delay>

  <statistics metering_dump="1000" per_url_stat="true"/>

  <request_constraints 
    sampling_size="10000"
    timeout="3000000"
    intended_time="2000000"
    failed_percentage="100"
    prolonged_percentage="100" />

  <url_list_file>@site_config_root@/tests/SearchFrontend/Requests.txt</url_list_file>

  <request>
    <scheduling>
      <stick_frequency period="40000" 
      />

<!--
                       decrease_by="5000"
                       decrease_to="1000"
                       decrease_every="10"
-->

    </scheduling>

    <headers>
      <header name="Accept-Encoding" value="gzip,deflate"/>
<!--
      <header name="Accept-Language" value="en-us"/>
      <header name="User-Agent" value="Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; .NET CLR 1.1.4322)"/>
-->
    </headers>

  </request>

</config>
